version: '3'
services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:25
    environment:
      - CLICKHOUSE_ADMIN_USER=admin
      - CLICKHOUSE_ADMIN_PASSWORD=admin
    ports:
      - '8123:8123'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
volumes:
  clickhouse_data:
    driver: local